language: java
jdk: openjdk11

sudo: enabled

before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE wj;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p123123
  - sudo service mysql restart
  # - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
  # - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" -uroot

# before_script:
#   - sudo mysql -e "use mysql;UPDATE user SET authentication_string=PASSWORD('Admin123!') WHERE user='root';"  -uroot

sevices:
  - mysql

script:
  - ./mvnw clean install -B